name: Test for merge from dev to main

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Start server in background
        run: npm run dev &

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3001

      - name: Run Cypress Component tests
        run: npm run test-component
